
skillMetadata:
  sections:
    - name: HA Settings
      fields:
        - name: hahost
          type: text
          label: HA Host url
          value: ""
          placeholder: http
        - name: hasecret
          type: text
          label: HA secret
          value: ""
          placeholder: ""
